spring:
  application:
    name: lifeline
  datasource:
    url: jdbc:mysql://localhost:3306/lifeline?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080

wechat:
  appid: wx29cd984ba7a6b475
  secret: 680fcab21851cbd5aa3179e29e036b89

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'group_1'
      paths-to-match: '/**'
      packages-to-scan: com.zazhi.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn